[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && java -jar target/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/stations"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 