# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Admin login config (used by your code for admin login)
admin.username=Admin
admin.password=AdminMFP123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}

# API base path
# spring.mvc.servlet.path=/api

# JWT Secret (DO NOT SHARE THIS IN PRODUCTION)
jwt.secret=8yF9nK2mP4qR7vX3jL5hC1tW6bN9cD0aE3uI8oZ2xM4

# PDF Output Directory
pdf.output.dir=./pdf-tokens 